"""Added disabled columns to main elements

Revision ID: ca7867709c7f
Revises: a74a175c5dce
Create Date: 2024-11-13 17:35:25.531033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7867709c7f'
down_revision: Union[str, None] = 'a74a175c5dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('disabled', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False))
    op.add_column('rooms', sa.Column('disabled', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False))
    op.add_column('objectives', sa.Column('disabled', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objectives', 'disabled')
    op.drop_column('rooms', 'disabled')
    op.drop_column('worlds', 'disabled')
    # ### end Alembic commands ###
